# Generated by Django 4.2.3 on 2023-07-29 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9_]+$")],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9_]+$")],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=30,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9_]+$")],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9_]+$")],
            ),
        ),
    ]
